import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'

export default function Top10() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ABOUT Top10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content='this is Blog'></meta>
      </Head>

    <h1 style={{color:"white"}}>Top10</h1>
      <p>
        This is the Top10 page
      </p>

    

     
    </div>
  )
}
