import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useState, useEffect } from 'react';


export default function Pokemon() {
    const [pokemonName, setPokemonName] = useState(null)
    useEffect(()=>{
        console.log('pokemon loaded')
        axios.get('https://pokeapi.co/api/v2/pokemon/steelix')
        .then((res)=>{
            console.log(res.data.name)
            setPokemonName(res.data.name)
        })
    }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon NEXTJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content='this is next js'></meta>
      </Head>

    <h1>Pokemon</h1>
      <p>
        This is the Pokemon page for {pokemonName}
      </p>

     
    </div>
  )
}
