import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useState, useEffect } from 'react';


export default function Pokemon() {
    useEffect(()=>{
        console.log('pokemon loaded')
    }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon NEXTJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content='this is next js'></meta>
      </Head>

    <h1>Pokemon</h1>
      <p>
        This is the Pokemon page
      </p>

     
    </div>
  )
}
